#!/bin/bash
# idepositbox
# (C) iDepositBox http://idepositbox.com
# chkconfig: - 98 02
#
# processname: idepositbox_cli

PATH=/usr/bin:/sbin:/bin:/usr/sbin
export PATH

IDEPO=/opt/idepositbox/bin/idepositbox_cli
run() {
  if id -u "idepositbox" >/dev/null 2>&1; then
	su idepositbox -s /bin/bash -c "$1 "
  else	
	exec "$1"
  fi
}

case "$1" in
    start)
        run "$IDEPO start"
    ;;
    stop)
        run "$IDEPO stop"
    ;;
    restart)
        run "$IDEPO stop"
	run "$IDEPO start"
    ;;
    reload|force-reload)
        run "$IDEPO reload"
    ;;
    status)
        run "$IDEPO status"
    ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|reload}"
        exit 1
esac

exit $RETVAL
