
RC_OK = 0
RC_ERROR = 1
RC_UNEXPECTED = -1
RC_REQ_CERTIFICATE = 1010

BUF_SIZE = 100*1024

FRI_CLIENT_TIMEOUT = 20
FRI_CLIENT_READ_TIMEOUT = None

#fri binary packet constants 
FRI_PROTOCOL_IDENTIFIER = 'FRI0'
FRI_PACKET_INFO_LEN = 20

