RC_NO_DATA = 324

DEFAULT_REPLICA_COUNT = 2
FRI_PORT = 1987
FRI_CLIENT_TIMEOUT = 60

CHUNK_SIZE = 64*1024*1024

FILE_ITER_BLOCK_SIZE = 1024*1024

RC_OK = 0
RC_ERROR = 1
RC_UNEXPECTED = -1

BUF_SIZE = 100*1024

FRI_CLIENT_TIMEOUT = 20
FRI_CLIENT_READ_TIMEOUT = None

#fri binary packet constants 
FRI_PROTOCOL_IDENTIFIER = 'FRI0'
FRI_PACKET_INFO_LEN = 20

FG_ERROR_TIMEOUT = 5

#security provider types
SPT_TOKEN_BASED = 'token'
SPT_FILE_BASED = 'file'

#usb token events
UTE_TOKEN_INSERTED = 1
UTE_TOKEN_REMOVED = 0
