RC_NO_DATA = 324

DEFAULT_REPLICA_COUNT = 2
FRI_PORT = 1987

MAX_DATA_BLOCK_SIZE = 64*1024*1024

FILE_ITER_BLOCK_SIZE = 1024*1024

FG_ERROR_TIMEOUT = 5

#security provider types
SPT_TOKEN_BASED = 'token'
SPT_FILE_BASED = 'file'

#usb token events
UTE_TOKEN_INSERTED = 1
UTE_TOKEN_REMOVED = 0

#async operation types
OT_SAVE = 'upload'
OT_LOAD = 'download'

ASYNC_WAIT_TIMEOUT = 0.1

#data block constants
BUF_LEN = 1024
READ_TRY_COUNT = 30
READ_SLEEP_TIME = 1
